### ISSUE TITLE
UPC A

### ISSUE THREAD

**Issue by commoedia** [Romanysoft/BarcodePro#1]
Hello we have a bug to create UPC A code; it don't work.
what i do?

thank you

Marco

![schermata 2015-08-27 alle 09 31 48](https://cloud.githubusercontent.com/assets/777836/9514966/770476e6-4c9e-11e5-9dd3-471d6e4540b9.png)

**Comment by lauer3912** [comment]
Oh, this is a serious bug. We repaired as quickly as possible, restored version will be sent to you. Thank you for the feedback.

**Comment by lauer3912** [comment]
@commoedia https://github.com/Romanysoft/BarcodePro/blob/master/publish/BarcodePro_8.0.zip
